
class COMMAND_ID:
    COMMAND_ID_INIT_WORKER = 1
    COMMAND_ID_GET_GPU_SUMMARY = 2
    COMMAND_ID_LAUNCH_TASK = 3

class OPERATION_ID:
    OPERATION_ID_WORKER_INITED = 1
    OPERATION_ID_UPDATE_GPU_SUMMARY = 2